// ALERT
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
// ARTISTS
export const LOADING_ARTISTS = 'LOADING_ARTISTS';
export const SAVING_ARTISTS = 'SAVING_ARTISTS';
export const GET_ARTISTS = 'GET_ARTISTS';
export const GET_ARTIST = 'GET_ARTIST';
export const ADD_ARTIST = 'ADD_ARTIST';
export const DELETE_ARTIST = 'DELETE_ARTIST';
export const UPDATE_ARTIST = 'UPDATE_ARTIST';
export const CLEAR_ARTISTS = 'CLEAR_ARTISTS';
// GENRES
export const LOADING_GENRES = 'LOADING_GENRES';
export const SAVING_GENRES = 'SAVING_GENRES';
export const GET_GENRES = 'GET_GENRES';
export const GET_GENRE = 'GET_GENRE';
export const ADD_GENRE = 'ADD_GENRE';
export const DELETE_GENRE = 'DELETE_GENRE';
export const UPDATE_GENRE = 'UPDATE_GENRE';
export const CLEAR_GENRES = 'CLEAR_GENRES';
// SINGLES
export const LOADING_SINGLES = 'LOADING_SINGLES';
export const SAVING_SINGLES = 'SAVING_SINGLES';
export const GET_SINGLES = 'GET_SINGLES';
export const GET_SINGLE = 'GET_SINGLE';
export const ADD_SINGLE = 'ADD_SINGLE';
export const DELETE_SINGLE = 'DELETE_SINGLE';
export const UPDATE_SINGLE = 'UPDATE_SINGLE';
export const CLEAR_SINGLES = 'CLEAR_SINGLES';
// ALBUMS
export const LOADING_ALBUMS = 'LOADING_ALBUMS';
export const SAVING_ALBUMS = 'SAVING_ALBUMS';
export const GET_ALBUMS = 'GET_ALBUMS';
export const GET_ALBUM = 'GET_ALBUM';
export const ADD_ALBUM = 'ADD_ALBUM';
export const DELETE_ALBUM = 'DELETE_ALBUM';
export const UPDATE_ALBUM = 'UPDATE_ALBUM';
export const CLEAR_ALBUMS = 'CLEAR_ALBUMS';
// PLAYLISTS
export const LOADING_PLAYLISTS = 'LOADING_PLAYLISTS';
export const SAVING_PLAYLISTS = 'SAVING_PLAYLISTS';
export const GET_PLAYLISTS = 'GET_PLAYLISTS';
export const GET_PLAYLIST = 'GET_PLAYLIST';
export const ADD_PLAYLIST = 'ADD_PLAYLIST';
export const DELETE_PLAYLIST = 'DELETE_PLAYLIST';
export const UPDATE_PLAYLIST = 'UPDATE_PLAYLIST';
export const CLEAR_PLAYLISTS = 'CLEAR_PLAYLISTS';
// THEME
export const SET_THEME = 'SET_THEME';
// PLAYER
export const SET_LOADING = 'SET_LOADING';
export const SET_PLAY = 'SET_PLAY';
export const SET_PAUSE = 'SET_PAUSE';
export const SET_DURATION = 'SET_DURATION';

export const ADD_TRACK = 'ADD_TRACK';
export const REMOVE_TRACK = 'REMOVE_TRACK';
export const SET_CURRENT_TRACK = 'SET_CURRENT_TRACK';
export const SET_NEXT_TRACK = 'SET_NEXT_TRACK';
export const SET_PREVIOUS_TRACK = 'SET_PREVIOUS_TRACK';
export const SHUFFLE = 'SHUFFLE';
export const SET_SHUFFLE = 'SET_SHUFFLE';
export const SET_REPEAT = 'SET_REPEAT';

// USER
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
